version: "3.8"
services:
  yolo:
    build: .
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/home/user/Documents/tensorRTForge
    privileged: true
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    working_dir: /home/user/Documents/tensorRTForge